import mongoose from "mongoose";
import {
  ARTICLE_STATUS,
  ARTICLE_STATUS_VALUES,
} from "#constants/articleStatus.js";

/**
 * ============================================================
 *  Article Model — Requirement 1, 14, 18 + supports all stages
 * ============================================================
 *
 *  An Article is the canonical document for one generation job.
 *  It accretes data as the pipeline progresses and survives
 *  all stage retries. Status transitions are atomic CAS updates
 *  performed by `articleRepository.transitionStatus()`.
 */

/* ── Sub-schemas (kept inline to avoid orphan exports) ── */

const sectionOutlineSchema = new mongoose.Schema(
  {
    heading: { type: String, required: true, trim: true },
    subPoints: { type: [String], default: [] },
    estimatedWordCount: { type: Number, required: true, min: 1 },
  },
  { _id: false }
);

const citationSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    bracketedNumeral: { type: Number, default: null }, // [1], [2], …
  },
  { _id: false }
);

const paragraphSchema = new mongoose.Schema(
  {
    id: { type: String, required: true }, // uuid v4 generated by Draft_Service
    html: { type: String, required: true },
    markdown: { type: String, default: "" },
    tag: {
      type: String,
      enum: ["factual", "intro", "transition", "opinion"],
      required: true,
    },
    citations: { type: [citationSchema], default: [] },
    wordCount: { type: Number, default: 0 },
  },
  { _id: false }
);

const sourceIndexSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    numeral: { type: Number, required: true }, // 1-based
  },
  { _id: false }
);

const seoSchema = new mongoose.Schema(
  {
    metaTitleOptions: { type: [String], default: [] }, // 3 candidates
    metaTitle: { type: String, default: null }, // user-chosen, defaults to options[0]
    metaDescription: { type: String, default: null },
    slug: { type: String, default: null },
    faq: {
      type: [
        new mongoose.Schema(
          {
            question: { type: String, required: true },
            answer: { type: String, required: true },
            citationUrls: { type: [String], default: [] },
          },
          { _id: false }
        ),
      ],
      default: [],
    },
    tags: { type: [String], default: [] },
    ogTitle: { type: String, default: null },
    ogDescription: { type: String, default: null },
    ogImage: { type: String, default: null },
  },
  { _id: false }
);

const flaggedSpanSchema = new mongoose.Schema(
  {
    sourceUrl: { type: String, required: true },
    sourceStartChar: { type: Number, required: true },
    sourceEndChar: { type: Number, required: true },
    articleStartChar: { type: Number, required: true },
    articleEndChar: { type: Number, required: true },
    tokenCount: { type: Number, required: true },
  },
  { _id: false }
);

const originalitySchema = new mongoose.Schema(
  {
    score: { type: Number, default: null }, // 0..1
    provider: { type: String, default: null },
    checkedAt: { type: Date, default: null },
    flaggedSpans: { type: [flaggedSpanSchema], default: [] },
    revisionAttempt: { type: Number, default: 0 },
  },
  { _id: false }
);

const costStageEntrySchema = new mongoose.Schema(
  {
    stageName: {
      type: String,
      enum: ["research", "outline", "draft", "seo", "originality"],
      required: true,
    },
    providerName: { type: String, required: true },
    model: { type: String, default: null },
    promptTokens: { type: Number, default: 0 },
    completionTokens: { type: Number, default: 0 },
    unitsConsumed: { type: Number, default: 0 },
    usdCost: { type: Number, default: 0 },
    costFlagged: { type: Boolean, default: false },
    latencyMs: { type: Number, default: 0 },
    ts: { type: Date, default: () => new Date() },
  },
  { _id: false }
);

const featuredImageSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    alt: { type: String, default: "" },
    source: { type: String, enum: ["unsplash", "upload", "ai"], required: true },
    sourceAttribution: {
      type: new mongoose.Schema(
        {
          photographerName: { type: String },
          photographerUrl: { type: String },
        },
        { _id: false }
      ),
      default: null,
    },
  },
  { _id: false }
);

const statusHistoryEntrySchema = new mongoose.Schema(
  {
    from: { type: String, required: true },
    to: { type: String, required: true },
    at: { type: Date, default: () => new Date() },
    reason: { type: String, default: null },
  },
  { _id: false }
);

/* ── Main schema ─────────────────────────────────────────── */

const articleSchema = new mongoose.Schema(
  {
    /* Tenant + ownership (Requirement 15, NFR6) */
    workspaceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Workspace",
      required: true,
      index: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    /* User input */
    topic: { type: String, required: true, trim: true, maxlength: 200 },
    targetKeyword: { type: String, required: true, trim: true, maxlength: 100 },
    additionalKeywords: { type: [String], default: [] },
    tone: {
      type: String,
      enum: ["Professional", "Casual", "Journalistic", "Academic"],
      default: "Professional",
    },
    targetWordCount: { type: Number, default: 1500, min: 300, max: 5000 },

    /* Lifecycle */
    status: {
      type: String,
      enum: ARTICLE_STATUS_VALUES,
      default: ARTICLE_STATUS.DRAFT,
      required: true,
      index: true,
    },
    statusHistory: { type: [statusHistoryEntrySchema], default: [] },
    failureReason: { type: String, default: null },
    jobId: { type: String, default: null, index: true, sparse: true },

    /* Stage outputs */
    researchBriefId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ResearchBrief",
      default: null,
    },
    outline: { type: [sectionOutlineSchema], default: [] },
    outlinePromptVersion: { type: String, default: null },

    paragraphs: { type: [paragraphSchema], default: [] },
    sourcesIndex: { type: [sourceIndexSchema], default: [] },
    contentHtml: { type: String, default: "" },
    contentMarkdown: { type: String, default: "" },
    wordCount: { type: Number, default: 0 },
    readingTimeMinutes: { type: Number, default: 0 },
    draftPromptVersion: { type: String, default: null },

    seo: { type: seoSchema, default: () => ({}) },
    originality: { type: originalitySchema, default: () => ({}) },
    featuredImage: { type: featuredImageSchema, default: null },

    /* Phase B agents (additive, all optional) */
    factCheck: {
      type: new mongoose.Schema(
        {
          verdict: { type: String, enum: ["pass", "revise"], default: "pass" },
          flags: { type: [Object], default: [] },
          summary: { type: String, default: "" },
          checkedAt: { type: Date, default: null },
        },
        { _id: false }
      ),
      default: null,
    },
    aiCitation: {
      type: new mongoose.Schema(
        {
          articleJsonLd: { type: Object, default: null },
          faqJsonLd: { type: Object, default: null },
          entityMentions: { type: [Object], default: [] },
          promptPatterns: { type: [String], default: [] },
          generatedAt: { type: Date, default: null },
        },
        { _id: false }
      ),
      default: null,
    },
    audience: {
      type: new mongoose.Schema(
        {
          personaName: { type: String, default: null },
          confidence: { type: Number, default: 0 },
          rationale: { type: String, default: "" },
          draftingHints: { type: [String], default: [] },
        },
        { _id: false }
      ),
      default: null,
    },
    socialPosts: {
      type: new mongoose.Schema(
        {
          twitterThread: { type: [String], default: [] },
          linkedinPost: { type: String, default: null },
          instagramCaption: { type: String, default: null },
          generatedAt: { type: Date, default: null },
        },
        { _id: false }
      ),
      default: null,
    },

    /* CMS publish (Requirement 9) */
    cmsConnectionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "CmsConnection",
      default: null,
    },
    cmsPostId: { type: String, default: null, index: true, sparse: true },
    cmsPostUrl: { type: String, default: null },
    publishedAt: { type: Date, default: null },
    scheduledAt: { type: Date, default: null },

    /* Cost tracking (Requirement 17) */
    costs: {
      type: new mongoose.Schema(
        {
          stages: { type: [costStageEntrySchema], default: [] },
          totalUsd: { type: Number, default: 0 },
        },
        { _id: false }
      ),
      default: () => ({ stages: [], totalUsd: 0 }),
    },

    /* Quota accounting */
    quotaIncrementApplied: { type: Boolean, default: false },
    quotaRefunded: { type: Boolean, default: false },

    /* View counters — denormalized for cheap list rendering. Maintained
       by the view-tracking pipeline; reset to 0 if we ever wipe ArticleView. */
    viewsTotal: { type: Number, default: 0, index: true },
    viewsLast30d: { type: Number, default: 0 },
    lastViewedAt: { type: Date, default: null },

    /* Moderation (platform-side) */
    moderation: {
      type: new mongoose.Schema(
        {
          flagged: { type: Boolean, default: false },
          flagReason: { type: String, default: null },
          flaggedAt: { type: Date, default: null },
          flaggedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
          },
          hidden: { type: Boolean, default: false },
          hiddenAt: { type: Date, default: null },
          hiddenBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
          },
        },
        { _id: false }
      ),
      default: () => ({}),
    },

    /* Soft delete (Requirement 18) */
    deletedAt: { type: Date, default: null, index: true },
  },
  { timestamps: true, versionKey: false }
);

/* Compound indexes — NFR6 */
articleSchema.index({ workspaceId: 1, _id: 1 });
articleSchema.index({ workspaceId: 1, createdAt: -1 });
articleSchema.index({ workspaceId: 1, status: 1 });
articleSchema.index({ workspaceId: 1, deletedAt: 1, createdAt: -1 });
// Tag-faceted listing
articleSchema.index({ workspaceId: 1, "seo.tags": 1 });
// Scheduled-publish scanner — find rows whose scheduledAt has elapsed
articleSchema.index(
  { status: 1, scheduledAt: 1 },
  {
    partialFilterExpression: {
      status: "scheduled",
      scheduledAt: { $type: "date" },
    },
    name: "scheduled_publish_scan",
  }
);
// Platform moderation page (cross-tenant flagged articles)
articleSchema.index(
  { "moderation.flagged": 1, createdAt: -1 },
  { partialFilterExpression: { "moderation.flagged": true } }
);
// Slug must be unique within a workspace (Requirement 5.5).
articleSchema.index(
  { workspaceId: 1, "seo.slug": 1 },
  { unique: true, partialFilterExpression: { "seo.slug": { $type: "string" } } }
);

export const Article = mongoose.model("Article", articleSchema);
export default Article;
