import mongoose from "mongoose";
import {
  ARTICLE_STATUS,
  ARTICLE_STATUS_VALUES,
  STAGE_NAMES,
  STAGE_STATUS,
  STAGE_STATUS_VALUES,
} from "#constants/articleStatus.js";

/**
 * ============================================================
 *  Article Model — Requirement 1, 14, 18 + supports all stages
 * ============================================================
 *
 *  An Article is the canonical document for one generation job.
 *  It accretes data as the pipeline progresses and survives
 *  all stage retries. Status transitions are atomic CAS updates
 *  performed by `articleRepository.transitionStatus()`.
 */

/* ── Sub-schemas (kept inline to avoid orphan exports) ── */

const sectionOutlineSchema = new mongoose.Schema(
  {
    heading: { type: String, required: true, trim: true },
    subPoints: { type: [String], default: [] },
    estimatedWordCount: { type: Number, required: true, min: 1 },
  },
  { _id: false }
);

const citationSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    bracketedNumeral: { type: Number, default: null }, // [1], [2], …
  },
  { _id: false }
);

const paragraphSchema = new mongoose.Schema(
  {
    id: { type: String, required: true }, // uuid v4 generated by Draft_Service
    html: { type: String, required: true },
    markdown: { type: String, default: "" },
    tag: {
      type: String,
      enum: ["factual", "intro", "transition", "opinion"],
      required: true,
    },
    citations: { type: [citationSchema], default: [] },
    wordCount: { type: Number, default: 0 },
  },
  { _id: false }
);

const sourceIndexSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    numeral: { type: Number, required: true }, // 1-based
  },
  { _id: false }
);

const seoSchema = new mongoose.Schema(
  {
    metaTitleOptions: { type: [String], default: [] }, // 3 candidates
    metaTitle: { type: String, default: null }, // user-chosen, defaults to options[0]
    metaDescription: { type: String, default: null },
    slug: { type: String, default: null },
    faq: {
      type: [
        new mongoose.Schema(
          {
            question: { type: String, required: true },
            answer: { type: String, required: true },
            citationUrls: { type: [String], default: [] },
          },
          { _id: false }
        ),
      ],
      default: [],
    },
    tags: { type: [String], default: [] },
    ogTitle: { type: String, default: null },
    ogDescription: { type: String, default: null },
    ogImage: { type: String, default: null },
  },
  { _id: false }
);

const flaggedSpanSchema = new mongoose.Schema(
  {
    sourceUrl: { type: String, required: true },
    sourceStartChar: { type: Number, required: true },
    sourceEndChar: { type: Number, required: true },
    articleStartChar: { type: Number, required: true },
    articleEndChar: { type: Number, required: true },
    tokenCount: { type: Number, required: true },
  },
  { _id: false }
);

const originalitySchema = new mongoose.Schema(
  {
    score: { type: Number, default: null }, // 0..1
    provider: { type: String, default: null },
    checkedAt: { type: Date, default: null },
    flaggedSpans: { type: [flaggedSpanSchema], default: [] },
    revisionAttempt: { type: Number, default: 0 },
  },
  { _id: false }
);

const costStageEntrySchema = new mongoose.Schema(
  {
    stageName: {
      type: String,
      enum: ["research", "outline", "draft", "seo", "originality"],
      required: true,
    },
    providerName: { type: String, required: true },
    model: { type: String, default: null },
    promptTokens: { type: Number, default: 0 },
    completionTokens: { type: Number, default: 0 },
    unitsConsumed: { type: Number, default: 0 },
    usdCost: { type: Number, default: 0 },
    costFlagged: { type: Boolean, default: false },
    latencyMs: { type: Number, default: 0 },
    ts: { type: Date, default: () => new Date() },
  },
  { _id: false }
);

const featuredImageSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    alt: { type: String, default: "" },
    source: { type: String, enum: ["unsplash", "upload", "ai"], required: true },
    sourceAttribution: {
      type: new mongoose.Schema(
        {
          photographerName: { type: String },
          photographerUrl: { type: String },
        },
        { _id: false }
      ),
      default: null,
    },
  },
  { _id: false }
);

const statusHistoryEntrySchema = new mongoose.Schema(
  {
    from: { type: String, required: true },
    to: { type: String, required: true },
    at: { type: Date, default: () => new Date() },
    reason: { type: String, default: null },
  },
  { _id: false }
);

/* ──────────────────────────────────────────────────────────
 *  Wizard mode subdocuments — Requirement 7 (Stage_Status
 *  persistence) + Requirement 2 (brief source selection) +
 *  Requirement 6 (publish step config).
 * ────────────────────────────────────────────────────────── */

const stageRecordSchema = new mongoose.Schema(
  {
    name: { type: String, enum: STAGE_NAMES, required: true },
    status: {
      type: String,
      enum: STAGE_STATUS_VALUES,
      default: STAGE_STATUS.PENDING,
    },
    startedAt: { type: Date, default: null },
    completedAt: { type: Date, default: null },
    approvedAt: { type: Date, default: null },
    retryCount: { type: Number, default: 0, min: 0 },
    chunkCount: { type: Number, default: 0, min: 0 },
    failureReason: { type: String, default: null },
    recoverable: { type: Boolean, default: false },
  },
  { _id: false }
);

const briefSelectionsSchema = new mongoose.Schema(
  {
    selectedCanonicalUrls: { type: [String], default: [] },
    updatedAt: { type: Date, default: null },
  },
  { _id: false }
);

const publishConfigSchema = new mongoose.Schema(
  {
    mode: {
      type: String,
      enum: ["draft", "now", "schedule"],
      default: "draft",
    },
    scheduledAt: { type: Date, default: null },
    cmsConnectionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "CmsConnection",
      default: null,
    },
    featuredImage: { type: featuredImageSchema, default: null },
    checklistOverride: { type: Boolean, default: false },
    checklistOverrideReason: { type: String, default: "" },
  },
  { _id: false }
);

/* ── Main schema ─────────────────────────────────────────── */

const articleSchema = new mongoose.Schema(
  {
    /* Tenant + ownership (Requirement 15, NFR6) */
    workspaceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Workspace",
      required: true,
      index: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    /* User input */
    topic: { type: String, required: true, trim: true, maxlength: 200 },
    targetKeyword: { type: String, required: true, trim: true, maxlength: 100 },
    additionalKeywords: { type: [String], default: [] },
    tone: {
      type: String,
      enum: ["Professional", "Casual", "Journalistic", "Academic"],
      default: "Professional",
    },
    targetWordCount: { type: Number, default: 1500, min: 300, max: 5000 },

    /**
     * Optional per-article brand voice. When set, the draft stage uses
     * THIS profile (looked up via brandVoiceRepository.findProfileById)
     * instead of the workspace-active one. Resolution order:
     *   1. article.brandVoiceProfileId (per-article opt-in)
     *   2. workspace's active profile
     *   3. no voice block
     */
    brandVoiceProfileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "BrandVoiceProfile",
      default: null,
    },

    /**
     * Optional template the article was created from. Used purely for
     * analytics/audit; the template's preset fields are copied onto the
     * article at creation time and not re-read.
     */
    templateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Template",
      default: null,
    },

    /* Lifecycle */
    status: {
      type: String,
      enum: ARTICLE_STATUS_VALUES,
      default: ARTICLE_STATUS.DRAFT,
      required: true,
      index: true,
    },
    statusHistory: { type: [statusHistoryEntrySchema], default: [] },
    failureReason: { type: String, default: null },
    jobId: { type: String, default: null, index: true, sparse: true },

    /* Stage outputs */
    researchBriefId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ResearchBrief",
      default: null,
    },
    outline: { type: [sectionOutlineSchema], default: [] },
    outlinePromptVersion: { type: String, default: null },

    /**
     * Outline Enricher output (Requirement 2.5, 6.4, 6.5).
     *
     * Populated by `outlineEnricherService.prepareOutlineContext` on
     * outline regenerate runs (never on the first outline pass) and
     * passed into `runOutlineStage` as a "Recharge context" prompt block.
     *
     * Optional and additive: `default: undefined` so absence on an
     * existing document is a valid state and never requires backfill.
     */
    outlineContext: {
      type: new mongoose.Schema(
        {
          extraAngles: { type: [String], default: [] },
          suggestedLinks: {
            type: [
              new mongoose.Schema(
                {
                  url: { type: String, required: true },
                  anchorHint: { type: String, default: "" },
                },
                { _id: false }
              ),
            ],
            default: [],
          },
          contrastFacts: {
            type: [
              new mongoose.Schema(
                {
                  factA: { type: String, required: true },
                  factB: { type: String, required: true },
                  sourceUrls: { type: [String], default: [] },
                },
                { _id: false }
              ),
            ],
            default: [],
          },
          audienceHook: { type: String, default: null },
          generatedAt: { type: Date, default: null },
        },
        { _id: false }
      ),
      default: undefined,
    },

    /**
     * Draft Formatter output (Requirement 4.3, 6.4, 6.5).
     *
     * Populated by `draftFormatterService.formatDraftHtml` after the
     * draft LLM call. Holds render-only formatting metadata that the
     * frontend can use for hero-paragraph styling and layout-aware
     * rendering. The top-level `paragraphs[]` field is NOT touched —
     * `draftFormatting.paragraphs[]` is a sibling additive collection
     * that mirrors the existing paragraph shape and adds optional
     * `displayHints` per paragraph.
     *
     * Optional and additive: `default: undefined` so absence on an
     * existing document is a valid state and never requires backfill.
     *
     * `displayHints.leadingHeadingLevel` (2 or 3) and
     * `displayHints.listKind` ("bullet" | "ordered" | null) are stored
     * without enum validators here; the value constraint is enforced
     * by the Draft Formatter at write time.
     */
    draftFormatting: {
      type: new mongoose.Schema(
        {
          formatVersion: { type: String, default: null },
          paragraphs: {
            type: [
              new mongoose.Schema(
                {
                  id: { type: String, required: true },
                  html: { type: String, required: true },
                  markdown: { type: String, default: "" },
                  tag: {
                    type: String,
                    enum: ["factual", "intro", "transition", "opinion"],
                    required: true,
                  },
                  citations: { type: [citationSchema], default: [] },
                  wordCount: { type: Number, default: 0 },
                  displayHints: {
                    type: new mongoose.Schema(
                      {
                        leadingHeadingLevel: { type: Number, default: null },
                        isOpening: { type: Boolean, default: null },
                        listKind: { type: String, default: null },
                        blockquote: { type: Boolean, default: null },
                      },
                      { _id: false }
                    ),
                    default: undefined,
                  },
                },
                { _id: false }
              ),
            ],
            default: [],
          },
        },
        { _id: false }
      ),
      default: undefined,
    },

    paragraphs: { type: [paragraphSchema], default: [] },
    sourcesIndex: { type: [sourceIndexSchema], default: [] },
    contentHtml: { type: String, default: "" },
    contentMarkdown: { type: String, default: "" },
    wordCount: { type: Number, default: 0 },
    readingTimeMinutes: { type: Number, default: 0 },
    draftPromptVersion: { type: String, default: null },

    seo: { type: seoSchema, default: () => ({}) },
    originality: { type: originalitySchema, default: () => ({}) },
    featuredImage: { type: featuredImageSchema, default: null },

    /* Phase B agents (additive, all optional) */
    factCheck: {
      type: new mongoose.Schema(
        {
          verdict: { type: String, enum: ["pass", "revise"], default: "pass" },
          flags: { type: [Object], default: [] },
          summary: { type: String, default: "" },
          checkedAt: { type: Date, default: null },
        },
        { _id: false }
      ),
      default: null,
    },
    aiCitation: {
      type: new mongoose.Schema(
        {
          articleJsonLd: { type: Object, default: null },
          faqJsonLd: { type: Object, default: null },
          entityMentions: { type: [Object], default: [] },
          promptPatterns: { type: [String], default: [] },
          generatedAt: { type: Date, default: null },
        },
        { _id: false }
      ),
      default: null,
    },
    audience: {
      type: new mongoose.Schema(
        {
          personaName: { type: String, default: null },
          confidence: { type: Number, default: 0 },
          rationale: { type: String, default: "" },
          draftingHints: { type: [String], default: [] },
        },
        { _id: false }
      ),
      default: null,
    },
    socialPosts: {
      type: new mongoose.Schema(
        {
          twitterThread: { type: [String], default: [] },
          linkedinPost: { type: String, default: null },
          instagramCaption: { type: String, default: null },
          generatedAt: { type: Date, default: null },
        },
        { _id: false }
      ),
      default: null,
    },

    /* CMS publish (Requirement 9) */
    cmsConnectionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "CmsConnection",
      default: null,
    },
    cmsPostId: { type: String, default: null, index: true, sparse: true },
    cmsPostUrl: { type: String, default: null },
    publishedAt: { type: Date, default: null },
    scheduledAt: { type: Date, default: null },

    /* Cost tracking (Requirement 17) */
    costs: {
      type: new mongoose.Schema(
        {
          stages: { type: [costStageEntrySchema], default: [] },
          totalUsd: { type: Number, default: 0 },
        },
        { _id: false }
      ),
      default: () => ({ stages: [], totalUsd: 0 }),
    },

    /* Quota accounting */
    quotaIncrementApplied: { type: Boolean, default: false },
    quotaRefunded: { type: Boolean, default: false },

    /* ── Wizard mode (Requirement 7, 2, 6) ─────────────────────
     * `wizardMode: true` is set when the article was created via
     * `POST /articles/wizard/start`. Stages run one at a time with
     * Approval_Gates between them. `wizardMode: false` is the
     * legacy one-shot Quick_Generate path which auto-approves.
     */
    wizardMode: { type: Boolean, default: false, index: true },
    stages: { type: [stageRecordSchema], default: [] },
    briefSelections: { type: briefSelectionsSchema, default: () => ({}) },
    publishConfig: { type: publishConfigSchema, default: () => ({}) },

    /* View counters — denormalized for cheap list rendering. Maintained
       by the view-tracking pipeline; reset to 0 if we ever wipe ArticleView. */
    viewsTotal: { type: Number, default: 0, index: true },
    viewsLast30d: { type: Number, default: 0 },
    lastViewedAt: { type: Date, default: null },

    /* Moderation (platform-side) */
    moderation: {
      type: new mongoose.Schema(
        {
          flagged: { type: Boolean, default: false },
          flagReason: { type: String, default: null },
          flaggedAt: { type: Date, default: null },
          flaggedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
          },
          hidden: { type: Boolean, default: false },
          hiddenAt: { type: Date, default: null },
          hiddenBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            default: null,
          },
        },
        { _id: false }
      ),
      default: () => ({}),
    },

    /* Soft delete (Requirement 18) */
    deletedAt: { type: Date, default: null, index: true },
  },
  { timestamps: true, versionKey: false }
);

/* Compound indexes — NFR6 */
articleSchema.index({ workspaceId: 1, _id: 1 });
articleSchema.index({ workspaceId: 1, createdAt: -1 });
articleSchema.index({ workspaceId: 1, status: 1 });
articleSchema.index({ workspaceId: 1, deletedAt: 1, createdAt: -1 });
// Tag-faceted listing
articleSchema.index({ workspaceId: 1, "seo.tags": 1 });
// Scheduled-publish scanner — find rows whose scheduledAt has elapsed
articleSchema.index(
  { status: 1, scheduledAt: 1 },
  {
    partialFilterExpression: {
      status: "scheduled",
      scheduledAt: { $type: "date" },
    },
    name: "scheduled_publish_scan",
  }
);
// Platform moderation page (cross-tenant flagged articles)
articleSchema.index(
  { "moderation.flagged": 1, createdAt: -1 },
  { partialFilterExpression: { "moderation.flagged": true } }
);
// Slug must be unique within a workspace (Requirement 5.5).
articleSchema.index(
  { workspaceId: 1, "seo.slug": 1 },
  { unique: true, partialFilterExpression: { "seo.slug": { $type: "string" } } }
);

export const Article = mongoose.model("Article", articleSchema);
export default Article;
